server:
  port: 8080

spring:
  application:
    name: shopapp-backend

  #config mysql8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${MYSQL_ROOT_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD:12042003}
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true

  #config file and multipart file
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # config multiple language (en, vi)
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en    # mặc định english

  #flayway
  flyway:
    locations: classpath:/db/migration, classpath:/dev/db/migration
    baseline-on-migrate: true   # phiên bản baseline = 1, không thực hiện bất kỳ thay đổi nào trong DB
    baseline-version: 0         # nó sẽ chạy V1__alter_some_tables.sql -> nghĩa là nó sẽ chạy cái version lớn hơn cái version hiện tại của chúng ta

  #redis memory
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": "category:com.hoangtien2k3.shopappbackend.models.Category"
    consumer:
      group-id: groupA
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

api:
  prefix: /api/v1
domain:
  protocol: http://localhost:${server.port}

jwt:
  expiration: 2592000 # 30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 # 60 days = 60 * 24 * 60 * 60
  secretKey: "QpOD7PxEqUCWRB8BU6e+Hv29TQLUuG+0sxxSJZWAPGhrVVszWZU2hT5RhoQTvhgv"

logging:
  level:
    org:
      springframework.security: DEBUG

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    filter: true
  #  api-docs:
  #    path: /api-docs
  show-actuator: true

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"
